SynProdGITV1/force-app/main/default/objects/Order/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>SSP-176 SS2-T109 How the Order got generated</description>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Order/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>SSP-176 SS2-T109 Division of Order</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Order/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSP-176 SS2-T109 Lookup to Plant object</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Order/fields/S4_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>S4_Order_Type__c</fullName>
    <description>SSP-176 Order types for S4 Hana</description>
    <label>S4 Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>S4_Order_Type</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Order/fields/Sales_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSP-176 SS2-T109 Lookup to Sales Organisation</description>
    <label>Sales Organisation</label>
    <referenceTo>Sales_Org_Data__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Order/fields/Salesforce_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Order_Type__c</fullName>
    <description>SSP-176 Order type for Salesforce and including S4 and Enorica</description>
    <label>Salesforce Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Salesforce_Order_Type</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Order/fields/Shipping_Condition__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Condition__c</fullName>
    <description>SSP-176 SS2-T109 How the shipping of Order is done.</description>
    <label>Shipping Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>02- Pick-up</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>03- Immediately</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>04- Transport Service</label>
            </value>
            <value>
                <fullName>CC</fullName>
                <label>CC- Consi / Ret. Issue</label>
            </value>
            <value>
                <fullName>RE</fullName>
                <label>RE- Returns</label>
            </value>
            <value>
                <fullName>ZA</fullName>
                <label>ZA- Airfreight</label>
            </value>
            <value>
                <fullName>ZB</fullName>
                <label>ZB- Courier</label>
            </value>
            <value>
                <fullName>ZC</fullName>
                <label>ZC- Groupage</label>
            </value>
            <value>
                <fullName>ZD</fullName>
                <label>ZD- Rail</label>
            </value>
            <value>
                <fullName>ZE</fullName>
                <label>ZE- Road</label>
            </value>
            <value>
                <fullName>ZF</fullName>
                <label>ZF- Sea</label>
            </value>
            <value>
                <fullName>ZG</fullName>
                <label>ZG- Self-collection</label>
            </value>
            <value>
                <fullName>ZH</fullName>
                <label>ZH- Barge</label>
            </value>
            <value>
                <fullName>ZI</fullName>
                <label>ZI- Intermodal</label>
            </value>
            <value>
                <fullName>ZL</fullName>
                <label>ZL- LTL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Default_Product_Used__c.field-meta.xml
<CustomField>
    <fullName>Default_Product_Used__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For sample order check if the default product is chose then make it true</description>
    <label>Default Product Used</label>
    <type>Checkbox</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>SSP-176 SS2-T109 Distribution Channel for the Distribution</description>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>SSP-176 SS2-T109 Division</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Estimated_Stock__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Stock__c</fullName>
    <description>Field to store the estimated stock at the time of OrderItem creation from Product Stock data - Stock Level.</description>
    <inlineHelpText>Available stock level at the time of order product creation.</inlineHelpText>
    <label>Estimated Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Is_Updated_From_Apex__c.field-meta.xml
<CustomField>
    <fullName>Is_Updated_From_Apex__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Inc 162773- Hidden checkbox to check if record updated from Apex or UI</description>
    <label>Is Updated From Apex?</label>
    <type>Checkbox</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSP-176 SS2-T109 Lookup to Plant Object from where the Product will come from</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Quantity_UoM__c.field-meta.xml
<CustomField>
    <fullName>Quantity_UoM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSP-176 SS2-T109 Lookup to Unit of Measure Object</description>
    <label>Quantity UoM</label>
    <referenceTo>UoM_Std_Data__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/S4_Item_Category__c.field-meta.xml
<CustomField>
    <fullName>S4_Item_Category__c</fullName>
    <description>SSP-176 SS2-T109 Product Category in S4</description>
    <label>S4 Item Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Item_Category</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/S4_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>S4_Order_Type__c</fullName>
    <description>SSP-176 SS2-T109 Order type in S4 Hana</description>
    <label>S4 Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZSAM</fullName>
                <label>ZSAM - S4 Sample Order</label>
            </value>
            <value>
                <fullName>ZBFD</fullName>
                <label>ZBFD - S4 FoC Order</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Sales_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSP-176 SS2-T109 Sales Orgnization for the Order</description>
    <label>Sales Organisation</label>
    <referenceTo>Sales_Org_Data__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Salesforce_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Order_Type__c</fullName>
    <description>SSP-176 SS2-T109 Order type in Salesforce</description>
    <label>Salesforce Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZSLS</fullName>
                <label>ZSLS - Enorica &amp; Lab Sample Order</label>
            </value>
            <value>
                <fullName>ZPLS</fullName>
                <label>ZPLS - S4 Sample Order</label>
            </value>
            <value>
                <fullName>ZOR</fullName>
                <label>ZOR - S4 Sales Order</label>
            </value>
            <value>
                <fullName>ZCRM</fullName>
                <label>ZCRM - CRM Samples</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Sample_Master_Matrix_Data__c.field-meta.xml
<CustomField>
    <fullName>Sample_Master_Matrix_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Sample Master Matrix data record</description>
    <label>Sample Master Matrix Data</label>
    <referenceTo>Sample_Master_Matrix_Data__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Shipping_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Date__c</fullName>
    <description>SSP-176 SS2-T109 Date on which Product will be shipeed for the current Order</description>
    <label>Shipping Date</label>
    <type>Date</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Total_Price_Internal__c.field-meta.xml
<CustomField>
    <fullName>Total_Price_Internal__c</fullName>
    <description>Total Price for internal calculation - this will be passed from SAP ERP. This will be used to calculate the Unit Price</description>
    <inlineHelpText>This will be passed from SAP ERP via API. This will be used to calculate the Unit Price</inlineHelpText>
    <label>Total Price (Internal)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SynProdGITV1/force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10 - Direct Sales</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20 - Intercompany</label>
    </customValue>
    <description>Specifies how products or services are delivered to customers</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

SynProdGITV1/force-app/main/default/globalValueSets/Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <label>00 - Common</label>
    </customValue>
    <description>Represents shared resources or operations applicable across all divisions</description>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

SynProdGITV1/force-app/main/default/globalValueSets/Item_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZSAF</fullName>
    </customValue>
    <customValue>
        <fullName>ZBXN</fullName>
    </customValue>
    <customValue>
        <fullName>ZFTF</fullName>
    </customValue>
    <description>Global picklist for S4 Item Categories</description>
    <masterLabel>Item Category</masterLabel>
</GlobalValueSet>

SynProdGITV1/force-app/main/default/globalValueSets/S4_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZSAM</fullName>
        <label>ZSAM - S4 Sample Order</label>
    </customValue>
    <customValue>
        <fullName>ZBFD</fullName>
        <label>ZBFD - S4 FoC Order</label>
    </customValue>
    <description>Order Type to be Used on Order, OLI, etc</description>
    <masterLabel>S4 Order Type</masterLabel>
</GlobalValueSet>

SynProdGITV1/force-app/main/default/globalValueSets/Salesforce_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZSLS</fullName>
        <label>ZSLS - Enorica &amp; Lab Sample Order</label>
    </customValue>
    <customValue>
        <fullName>ZPLS</fullName>
        <label>ZPLS - S4 Sample Order</label>
    </customValue>
    <customValue>
        <fullName>ZOR</fullName>
        <label>ZOR - S4 Sales Order</label>
    </customValue>
    <customValue>
        <fullName>ZCRM</fullName>
        <label>ZCRM - CRM Samples</label>
    </customValue>
    <description>Order Type to be Used on Order, OLI, etc</description>
    <masterLabel>Salesforce Order Type</masterLabel>
</GlobalValueSet>

SynProdGITV1/force-app/main/default/classes/Syn_UpdateOrderProductsController.cls
/*************************************************************** 
====================================================== 
Purpose: 
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   28/04/2025    SSP-353	    Initial Implementation	
Vishal S   16/07/2025    INC.159398     Shipping Country is missing while Evaluating sold to Party
Vishal S   21/07/2025    INC.159362    Determine the currency for non ZPLS sample order
Shyam C    09/08/2025    INC 162773    Making is_Updated_From_Apex__c = True to bypass validations written in a flow.
Vishal S   22/09/2025	 INC.164768		Remove validation for ZBFD - S4 Order type 
Ankur O   29/10/2025     Community Portal  Added Methods to Determine Portal User and Account Region.
***************************************************************/ 
public without sharing class Syn_UpdateOrderProductsController{
    
    /*************************************************************** 
====================================================== 
Purpose: 
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   28/04/2025    SSP-353	    Initial Implementation
Shyam C    09/08/2025    INC 162773+    Making is_Updated_From_Apex__c = True to bypass validations written in a flow.
***************************************************************/ 
    @AuraEnabled
    public static boolean updateOrderProducts(List<Map<String, Object>> orderProduct, Id orderId) {
        
        
        // Retrieve existing OrderItems for the given OrderId
        Map<String, OrderItem> existingItemsMap = new Map<String, OrderItem>();
        List<OrderItem> existingItems = new List<OrderItem>();
        for (OrderItem oi : [SELECT Id, Sample_Master_Matrix_Data__c, Default_Product_Used__c, Quantity, Total_Price_Internal__c, OrderId FROM OrderItem WHERE OrderId = :orderId]) {
            existingItemsMap.put(oi.Sample_Master_Matrix_Data__c, oi);
            existingItems.add(oi);
        }
        // Get Order details
        Order order = [SELECT Id, Pricebook2Id, CurrencyIsoCode FROM Order WHERE Id = : orderId LIMIT 1];
        
        // These are common for all products
        Id pricebook2Id = order.Pricebook2Id;
        String currencyIsoCode = order.CurrencyIsoCode;
        
        // Collect unique Product2Ids
        Set<Id> productIds = new Set<Id>();
        for (Map<String, Object> item : orderProduct) {
            productIds.add((Id)item.get('productId'));
        }
        
        // Query all needed PricebookEntries
        Map<Id, Id> productToPbeIdMap = new Map<Id, Id>();
        List<PricebookEntry> pbeList = [
            SELECT Id, Product2Id
            FROM PricebookEntry
            WHERE Pricebook2Id = :pricebook2Id
            AND CurrencyIsoCode = :currencyIsoCode
            AND Product2Id IN :productIds
        ];
        
        for (PricebookEntry pbe : pbeList) {
            productToPbeIdMap.put(pbe.Product2Id, pbe.Id);
        }
        
        
        // Prepare lists for DML operations
        List<OrderItem> itemsToInsert = new List<OrderItem>();
        List<OrderItem> itemsToUpdate = new List<OrderItem>();
        List<OrderItem> itemsToDelete = new List<OrderItem>();
        
        // Process each item in the incoming orderProduct list
        for (Map<String, Object> item : orderProduct) {
            String itemId = (String)item.get('Id');
            OrderItem existingItem = existingItemsMap.get(itemId);
            System.debug('item '+  (Decimal)item.get('unitPrice'));
            // Create or update OrderItem
            //OrderItem orderItem = existingItem != null ? existingItem : new OrderItem();
            
           Id productId = (Id)item.get('productId');
        	Id pricebookEntryId = productToPbeIdMap.get(productId);
            
            OrderItem orderItem = new OrderItem();
            
            if(existingItem == null){
                
                orderItem.OrderId = orderId;
                orderItem.Sample_Master_Matrix_Data__c = itemId;
                orderItem.Product2Id = productId;
                //orderItem.PricebookEntryId = (String)item.get('pricebookEntryId');
                orderItem.PricebookEntryId = pricebookEntryId;
                orderItem.Quantity = (Decimal)item.get('quantity');
                //orderItem.UnitPrice = (Decimal)item.get('unitPrice');
                orderItem.Total_Price_Internal__c = (Decimal)item.get('totalPrice');
                orderItem.Description = (String)item.get('description');
                orderItem.Plant__c = (String)item.get('plantId');
                orderItem.Salesforce_Order_Type__c = (String)item.get('SalesforceOrderType');
                orderItem.S4_Order_Type__c = (String)item.get('s4OrderType');
                orderItem.S4_Item_Category__c = (String)item.get('itemCategory');
                orderItem.Sales_Organisation__c = (String)item.get('salesOrg');
                orderItem.Distribution_Channel__c = (String)item.get('distributionChannel');
                orderItem.Division__c = (String)item.get('division');
                orderItem.Quantity_UoM__c = (String)item.get('uomId');
                orderItem.Default_Product_Used__c = (Boolean)item.get('isDefaultProduct');
                if ( item.get('stockLevel') != null) {
                    orderItem.Estimated_Stock__c = Decimal.valueOf(String.valueOf(item.get('stockLevel')));
                } else {
                    orderItem.Estimated_Stock__c = null; // Or set to 0 if that's preferred
                }
                if (item.containsKey('shippingDate')) {
                    orderItem.Shipping_Date__c = (Date)item.get('shippingDate');
                }
                
                
                itemsToInsert.add(orderItem);
            } else {
                
                if (existingItem != null) {
                Decimal newQty = (Decimal)item.get('quantity');
                Decimal oldQty = existingItem.Quantity;

                Boolean isDefault = existingItem.Default_Product_Used__c;
                Boolean isQtyChanged = oldQty != newQty;

                if (isQtyChanged) {
                    orderItem.Id = existingItem.Id;
                    orderItem.Quantity = newQty;
                    orderItem.Total_Price_Internal__c = (Decimal)item.get('totalPrice');
                    
                    orderItem.Is_Updated_From_Apex__c = True;  //INC 162773+ Shyam C - Turning Flag up to bypass validations in a flow.
                    
                    itemsToUpdate.add(orderItem);
                } else if(isDefault){
                    orderItem.Id = existingItem.Id;
                    orderItem.Description = (String)item.get('description');
                    
                    orderItem.Is_Updated_From_Apex__c = True;  //INC 162773+ Shyam C - Turning Flag up to bypass validations in a flow.
                    
                    itemsToUpdate.add(orderItem);
                }
            }
                
            }
            
            // Remove the processed item from the map
            existingItemsMap.remove(itemId);
        }
        
        // Identify OrderItems to delete (those not in the incoming list)
        for (OrderItem obsoleteItem : existingItemsMap.values()) {
            itemsToDelete.add(obsoleteItem);
        }
        
        System.debug(itemsToInsert);
        System.debug(itemsToUpdate);
        System.debug(itemsToDelete);
        
        // Perform DML operations
        try {
            if (!itemsToDelete.isEmpty()) {
                delete itemsToDelete;
            }
            if (!itemsToInsert.isEmpty()) {

                String newCurrencyIsoCode = currencyIsoCode;
                
                if(!itemsToDelete.isEmpty() || existingItems.isEmpty()){
                    if(checkItemToDeleteWithExistingItems(existingItems, itemsToDelete )){

                        newCurrencyIsoCode = updateOrderHeader(itemsToInsert, orderProduct);
                        
                    }
                }

                if(newCurrencyIsoCode!= currencyIsoCode)
                {
                    // Query all needed PricebookEntries
                    Map<Id, Id> newProductToPbeIdMap = new Map<Id, Id>();
                    List<PricebookEntry> newPbeList = [
                        SELECT Id, Product2Id
                        FROM PricebookEntry
                        WHERE Pricebook2Id = :pricebook2Id
                        AND CurrencyIsoCode = :newCurrencyIsoCode
                        AND Product2Id IN :productIds
                    ];
                    
                    for (PricebookEntry pbe : newPbeList) {
                        newProductToPbeIdMap.put(pbe.Product2Id, pbe.Id);
                    }

                    for(OrderItem orderItem : itemsToInsert){
                        Id pbeId = newProductToPbeIdMap.get(orderItem.Product2Id);
                        orderItem.PricebookEntryId = pbeId;
                    }
                }

                insert itemsToInsert;
            }
            if (!itemsToUpdate.isEmpty()) {

                update itemsToUpdate;
            }


            
        } catch (DmlException e) {
            System.debug(e.getMessage());
            throw new AuraHandledException('Error updating Order Line Items: ' + e.getMessage());
        }

        if(itemsToInsert.isEmpty() && itemsToUpdate.isEmpty() && itemsToDelete.isEmpty()){
            return false;
        }
            else{
                return true;
            }
    }
    
    /*************************************************************** 
====================================================== 
Purpose: 
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   28/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/ 
    
    
    public static boolean checkItemToDeleteWithExistingItems(List<OrderItem> existingItems, List<OrderItem> itemsToDelete){
        
        List<Id> existingItemSampleMatrixIds = new List<Id>();
        List<Id> itemsToDeleteSampleMatrixIds = new List<Id>();
        
        for (OrderItem oi : existingItems) {
            if (oi.Sample_Master_Matrix_Data__c != null) {
                existingItemSampleMatrixIds.add(oi.Sample_Master_Matrix_Data__c);
            }
        }
        
        for(OrderItem oi: itemsToDelete){
            if (oi.Sample_Master_Matrix_Data__c != null) {
                itemsToDeleteSampleMatrixIds.add(oi.Sample_Master_Matrix_Data__c);
            }
        }
        
        if (existingItemSampleMatrixIds.equals(itemsToDeleteSampleMatrixIds)) {
            System.debug('all to delete');
            return true;
        }
        return false;
        
    }
    
    /*************************************************************** 
====================================================== 
Purpose: 
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   28/04/2025    SSP-353	    Initial Implementation
Vishal S   16/07/2025    INC.159398     Shipping Country is missing while Evaluating sold to Party
Vishal S   21/07/2025    INC.159362    Determine the currency for non ZPLS sample order
Vishal S   22/09/2025	 INC.164768		Remove validation for ZBFD - S4 Order type  
***************************************************************/ 
    
    
   public static String updateOrderHeader(List<OrderItem> itemsToInsert, List<Map<String, Object>> orderProduct) {
    if (itemsToInsert == null || itemsToInsert.isEmpty() || orderProduct == null || orderProduct.isEmpty()) {
        throw new AuraHandledException('Order data is incomplete.');
    }

    Id orderId = itemsToInsert[0].OrderId;
    Order orderToUpdate = [SELECT Id, Plant__c, Sales_Organisation__c, Salesforce_Order_Type__c, S4_Order_Type__c, 
        Distribution_Channel__c, Division__c, Shipping_Condition__c, Delivery_Block__c, AccountId, ShippingCountry,
        IncoTerms__c, IncoTerms_Location__c, CurrencyIsoCode, Payment_Terms__c, Evaluated_Sold_To_Party__c,  
        Ship_To_Account__r.CurrencyIsoCode, Account.CurrencyIsoCode, Ship_To_Account__c,
        //changes start for INC.159398 16-07-2025
        Account.BillingCountry, Account.ShippingCountry, 
        Ship_To_Account__r.ShippingCountry, Ship_To_Account__r.BillingCountry
        //changes end for INC.159398 16-07-2025
        FROM Order 
        WHERE Id = :orderId LIMIT 1];

    // Basic field mapping
    orderToUpdate.Plant__c = itemsToInsert[0].Plant__c;
    orderToUpdate.Sales_Organisation__c = itemsToInsert[0].Sales_Organisation__c;
    orderToUpdate.Salesforce_Order_Type__c = itemsToInsert[0].Salesforce_Order_Type__c;
    orderToUpdate.S4_Order_Type__c = itemsToInsert[0].S4_Order_Type__c;
    orderToUpdate.Distribution_Channel__c = itemsToInsert[0].Distribution_Channel__c;
    orderToUpdate.Division__c = itemsToInsert[0].Division__c;
    orderToUpdate.Shipping_Condition__c = (String)orderProduct[0].get('shippingCondition');
    orderToUpdate.Delivery_Block__c = (String)orderProduct[0].get('deliveryBlock');

    // ZPLS-specific logic
    if (orderToUpdate.Salesforce_Order_Type__c == 'ZPLS') {
        //changes start for INC.159398 16-07-2025
        String orderShippingCountry;

        if (orderToUpdate.Ship_To_Account__c != null) {
            orderShippingCountry = (orderToUpdate.Ship_To_Account__r.ShippingCountry != null) 
                ? orderToUpdate.Ship_To_Account__r.ShippingCountry 
                : orderToUpdate.Ship_To_Account__r.BillingCountry;
        } else {
            orderShippingCountry = (orderToUpdate.Account.ShippingCountry != null)
                ? orderToUpdate.Account.ShippingCountry
                : orderToUpdate.Account.BillingCountry;
        }

        Syn_CreateOrderController.EvaluatedAccountInfo info = Syn_CreateOrderController.getEvaluatedSoldToParty(
            orderToUpdate.AccountId, orderToUpdate.Plant__c, orderShippingCountry
        ); 
        // changes end for INC.159398 16-07-2025
        // Begin of for INC. 164768 - 22/09/2025 - Vishal S 
       //if (info.evaluatedSoldToParty != orderToUpdate.AccountId && orderToUpdate.S4_Order_Type__c == 'ZBFD') {
       //    throw new AuraHandledException('Sample Product cannot be selected for the selected Account. Please ask the CSR team to create the Sample order directly in S4.');
       // }
        //End of for INC. 164768 - 22/09/2025 - Vishal S 

        orderToUpdate.IncoTerms__c = info.incoTerms;
        orderToUpdate.IncoTerms_Location__c = info.incotermLocation;
        orderToUpdate.Payment_Terms__c = info.paymentTerm;
        orderToUpdate.Evaluated_Sold_To_Party__c = info.evaluatedSoldToParty;
        orderToUpdate.CurrencyIsoCode = info.currencyIsoCode;
    } else {
         orderToUpdate.IncoTerms__c = '';
         orderToUpdate.IncoTerms_Location__c = '';
         orderToUpdate.Payment_Terms__c = null;
         orderToUpdate.Evaluated_Sold_To_Party__c = null;
        //Begin of for INC. 159362- 21/07/2025 - Vishal S 
        // 
        // orderToUpdate.CurrencyIsoCode = (orderToUpdate.Ship_To_Account__r.CurrencyIsoCode != null)
        //     ? orderToUpdate.Ship_To_Account__r.CurrencyIsoCode
        //     : orderToUpdate.Account.CurrencyIsoCode;
       // Ends of INC. 159362- 21/07/2025 - Vishal S

       //Begin of INC. 159362+ 21/07/2025 - Vishal S
        String orderCurrency = Syn_CreateOrderController.getNonS4OrderCurrency(orderToUpdate.AccountId, orderToUpdate.Plant__c);
		System.debug(orderToUpdate.Plant__c + ' ' + orderCurrency);
        orderToUpdate.CurrencyIsoCode = orderCurrency;
        // Ends of INC. 159362+ 21/07/2025 - Vishal S
    }

    update orderToUpdate;
    return orderToUpdate.CurrencyIsoCode;
}
/*************************************************************** 
====================================================== 
Purpose: 
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Ankur O   29/09/2025    Community Portal Method to determine Partner User Login	 
***************************************************************/  
    @AuraEnabled
    public static Boolean isPartnerUser() {
        return [SELECT Id, IsPartner FROM User WHERE Id = :UserInfo.getUserId()]
               .IsPartner;
    }
/*************************************************************** 
====================================================== 
Purpose: 
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Ankur O   29/09/2025    Community Portal Method to determine Account Region	 	 
***************************************************************/     
    @AuraEnabled
    public static String getAccountRegion() {
        Id accId=  [SELECT Id, AccountId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1].AccountId;
        List<Account> lstAccount = [SELECT Id,Region__c FROM Account WHERE Id = : accId];
        Account objAccount = lstAccount[0];
        return objAccount.Region__c;
        
        
    }   

       
}