SynProdGITV1/force-app/main/default/objects/Order/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>SSP-176 SS2-T109 How the Order got generated</description>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Order/fields/Salesforce_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Order_Type__c</fullName>
    <description>SSP-176 Order type for Salesforce and including S4 and Enorica</description>
    <label>Salesforce Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Salesforce_Order_Type</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Salesforce_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Order_Type__c</fullName>
    <description>SSP-176 SS2-T109 Order type in Salesforce</description>
    <label>Salesforce Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZSLS</fullName>
                <label>ZSLS - Enorica &amp; Lab Sample Order</label>
            </value>
            <value>
                <fullName>ZPLS</fullName>
                <label>ZPLS - S4 Sample Order</label>
            </value>
            <value>
                <fullName>ZOR</fullName>
                <label>ZOR - S4 Sales Order</label>
            </value>
            <value>
                <fullName>ZCRM</fullName>
                <label>ZCRM - CRM Samples</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Sample_Master_Matrix_Data__c.field-meta.xml
<CustomField>
    <fullName>Sample_Master_Matrix_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Sample Master Matrix data record</description>
    <label>Sample Master Matrix Data</label>
    <referenceTo>Sample_Master_Matrix_Data__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>Complete Plant Data</description>
    <label>Plant Data</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Plant__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <externalId>true</externalId>
    <label>Plant ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product2/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <description>For ERP products - this will be populated by ERP&apos;s MATNR Number 
For Salesforce Products - this will be populated by Internal Product ID which is an AutoNumber 10000000 onwards
(We might need to turn off the Unique flag during the migration of C4C Products if Product ID will be blank)</description>
    <externalId>true</externalId>
    <inlineHelpText>For ERP products - MATNR 
For Salesforce Product - Internal Product ID (AutoNumber)</inlineHelpText>
    <label>Product Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - Product Hierarchy</fullName>
            </value>
            <value>
                <fullName>2 - Chemical Group</fullName>
            </value>
            <value>
                <fullName>3 - Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/fields/Product_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_ID__c</fullName>
    <externalId>true</externalId>
    <label>Product Category ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Sales_Data__c/Product_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Product Sales Data</label>
    <nameField>
        <displayFormat>PSD-{00000000}</displayFormat>
        <label>Product Sales Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Sales Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Product_Sales_Data__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product ID</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Sales Data</relationshipLabel>
    <relationshipName>Product_Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Stock_Data__c/Product_Stock_Data__c.object-meta.xml
<CustomObject>
    <label>Product Stock Data</label>
    <nameField>
        <displayFormat>PSDM-{00000000}</displayFormat>
        <label>Product Stock Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stock Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Product_Stock_Data__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product ID</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Stock Data</relationshipLabel>
    <relationshipName>Product_Stock_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Stock_Data__c/fields/Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Stock_Level__c</fullName>
    <label>Stock Level</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Salesforce_Order_Type_Determination__c/Salesforce_Order_Type_Determination__c.object-meta.xml
<CustomObject>
    <description>Object to store the mapping between Sample Product and &quot;Plant, Salesforce order type, Sales Area, etc&quot;</description>
    <label>Salesforce Order Type Determination Data</label>
    <nameField>
        <displayFormat>SOT-{00000000}</displayFormat>
        <label>Salesforce Order Type Determinat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Order Type Determination</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Salesforce_Order_Type_Determination__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to plant data</description>
    <label>Plant ID</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipName>Salesforce_Order_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Salesforce_Order_Type_Determination__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Sales org data object</description>
    <label>Sales Org</label>
    <referenceTo>Sales_Org_Data__c</referenceTo>
    <relationshipName>Salesforce_Order_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Salesforce_Order_Type_Determination__c/fields/Salesforce_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Order_Type__c</fullName>
    <label>Salesforce Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Salesforce_Order_Type</valueSetName>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/Sample_Master_Matrix_Data__c.object-meta.xml
<CustomObject>
    <label>Sample Master Matrix Data</label>
    <nameField>
        <label>Sample Master Matrix Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Master Matrix Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Min__c.field-meta.xml
<CustomField>
    <fullName>Min__c</fullName>
    <label>Min</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plant ID</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Product_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Only Product Categories are allowed</inlineHelpText>
    <label>Product Category ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>3 - Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region field for region specific products</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASIA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Sampling_Status__c.field-meta.xml
<CustomField>
    <fullName>Sampling_Status__c</fullName>
    <label>Sampling Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01 - In Preparation</fullName>
            </value>
            <value>
                <fullName>02 - Active</fullName>
            </value>
            <value>
                <fullName>03 - Blocked</fullName>
            </value>
            <value>
                <fullName>04 - Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>UoM_Std_Data__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/UoM_Std_Data__c/UoM_Std_Data__c.object-meta.xml
<CustomObject>
    <label>UoM Std Data</label>
    <nameField>
        <label>Measurement Unit Text</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UoM Std Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/UoM_Std_Data__c/fields/UOM_Code__c.field-meta.xml
<CustomField>
    <fullName>UOM_Code__c</fullName>
    <description>ISO Code</description>
    <externalId>true</externalId>
    <inlineHelpText>ISO Code - this will be used in Material integration and migration</inlineHelpText>
    <label>UOM Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/globalValueSets/Distribution_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10 - Direct Sales</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20 - Intercompany</label>
    </customValue>
    <description>Specifies how products or services are delivered to customers</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

SynProdGITV1/force-app/main/default/globalValueSets/Salesforce_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZSLS</fullName>
        <label>ZSLS - Enorica &amp; Lab Sample Order</label>
    </customValue>
    <customValue>
        <fullName>ZPLS</fullName>
        <label>ZPLS - S4 Sample Order</label>
    </customValue>
    <customValue>
        <fullName>ZOR</fullName>
        <label>ZOR - S4 Sales Order</label>
    </customValue>
    <customValue>
        <fullName>ZCRM</fullName>
        <label>ZCRM - CRM Samples</label>
    </customValue>
    <description>Order Type to be Used on Order, OLI, etc</description>
    <masterLabel>Salesforce Order Type</masterLabel>
</GlobalValueSet>

SynProdGITV1/force-app/main/default/classes/Syn_ProductSelectorController.cls
/*************************************************************** 
====================================================== 
Purpose: Product Selector LWC controller class
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/ 
public with sharing class Syn_ProductSelectorController {
    
    
    /*************************************************************** 
====================================================== 
Purpose: Retrive products based user input values
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/ 
    @AuraEnabled(cacheable=true)
    public static SampleSearchResult searchProducts(String productName, String categoryName, String unitOfMeasureName, String requiredQuantity, String region, Integer pageNumber,
    Integer pageSize) {
        System.debug('pageNumber:'+pageNumber);
        Integer safePageNumber = (pageNumber == null || pageNumber < 1) ? 1 : pageNumber;
        List<SampleMasterMatrixWrapper> wrappedResults = new List<SampleMasterMatrixWrapper>();
          SampleSearchResult resultWrapper = new SampleSearchResult();
        Integer totalRecords = 0;
        
        if(productName == null && categoryName == null ){
            resultWrapper.records = wrappedResults;
           resultWrapper.totalRecords = 0;
           return resultWrapper;
        }

        // Add wildcards for partial match
        String nameFilter = '%' + productName.replace('*', '%') + '%';
        String categoryFilter = (categoryName != null && categoryName != '') ? '%' + categoryName.replace('*', '%') + '%' : null;
        String unitOfMeasureFilter = (unitOfMeasureName != null && unitOfMeasureName != '') ? '%' + unitOfMeasureName.replace('*', '%') + '%' : null;
        String regionFilter = (region != null && region != '') ? '%' + region + '%' : null;
        Decimal requiredQty = (requiredQuantity != null && requiredQuantity != '')?Decimal.valueOf(requiredQuantity):null;
        String samplingStatus = '02 - Active';

        System.debug(nameFilter + ' '+ categoryFilter + ' '+ unitOfMeasureFilter);
        
          // Apply LIMIT and OFFSET
       Integer offsetVal = (safePageNumber - 1) * pageSize;
       // Get total count
      String countQuery = 'SELECT COUNT() FROM Sample_Master_Matrix_Data__c WHERE Sampling_Status__c  =: samplingStatus';

        // Start building the query string
        String query = 'SELECT Id, Name, Product__c, Plant_ID__c, Product__r.Product_Id__c, Product__r.Name, Product_Category_ID__r.Name, Plant_ID__r.Name, ' +
            'Min__c, Max__c, Product__r.StockKeepingUnit, Unit__r.Name, Region__c, Sampling_Status__c ' +
            'FROM Sample_Master_Matrix_Data__c WHERE Sampling_Status__c  =: samplingStatus' ;
            
         
            query += ' AND Product__r.Name LIKE \'' + String.escapeSingleQuotes(nameFilter) + '\'';
            countQuery += ' AND Product__r.Name LIKE \'' + String.escapeSingleQuotes(nameFilter) + '\'';
    

        if (categoryFilter != null) {
            query += ' AND Product_Category_ID__r.Name LIKE \'' + String.escapeSingleQuotes(categoryFilter) + '\'';
             countQuery += ' AND Product_Category_ID__r.Name LIKE \'' + String.escapeSingleQuotes(categoryFilter) + '\'';
        }
        
        if(unitOfMeasureFilter != null) {
            query += 'AND (Unit__r.Name LIKE \'' + String.escapeSingleQuotes(unitOfMeasureFilter) + '\' OR Unit__r.UOM_Code__c LIKE \'' + String.escapeSingleQuotes(unitOfMeasureFilter) + '\')';
            countQuery += 'AND (Unit__r.Name LIKE \'' + String.escapeSingleQuotes(unitOfMeasureFilter) + '\' OR Unit__r.UOM_Code__c LIKE \'' + String.escapeSingleQuotes(unitOfMeasureFilter) + '\')';
        }
        
        if(regionFilter != null){
            query += ' AND (Region__c LIKE \'' + String.escapeSingleQuotes(regionFilter) + '\' OR Region__c = null OR Region__c = \'\')';
            countQuery += ' AND (Region__c LIKE \'' + String.escapeSingleQuotes(regionFilter) + '\' OR Region__c = null OR Region__c = \'\')';
        }
       
        query += ' ORDER BY Min__c ASC';
        query += ' LIMIT ' + pageSize + ' OFFSET ' + offsetVal;
       
        
        // Execute the dynamic SOQL query
        List<Sample_Master_Matrix_Data__c> lstProductSampleMasterMatrixData = Database.query(query);
        totalRecords = (Integer) Database.countQuery(countQuery);
        List<Sample_Master_Matrix_Data__c> finalListProductSampleMasterMatrixData = new List<Sample_Master_Matrix_Data__c>();
        // Boolean blnQty = false;
        
        // if(requiredQty!= null){
        //     for (Sample_Master_Matrix_Data__c record : lstProductSampleMasterMatrixData) {
        //         // You can access fields like:
        //         Decimal minQty = record.Min__c;
        //         Decimal maxQty = record.Max__c;
                
        //         if(requiredQty <= maxQty && requiredQty >= minQty){
                    
        //             if(!blnQty){
        //             finalListProductSampleMasterMatrixData.clear();
        //             }
        //             finalListProductSampleMasterMatrixData.add(record);
        //             blnQty = true;
        //             continue;
        //         }else if(requiredQty <= minQty && !blnQty){
        //             finalListProductSampleMasterMatrixData.add(record);
        //             continue;
        //         }else if(requiredQty >=minQty && !blnQty){
        //             finalListProductSampleMasterMatrixData.clear();
        //             finalListProductSampleMasterMatrixData.add(record);        
        //         }
                
        //         // Example debug log
        //         System.debug('Product: ' + productName + ', Region: ' + region);
        //     }
        // }
        // else{
        //     finalListProductSampleMasterMatrixData.addAll(lstProductSampleMasterMatrixData);
        // }
        
        finalListProductSampleMasterMatrixData.addAll(lstProductSampleMasterMatrixData);

        List<Id> productIds = new List<Id>();
        
        for (Sample_Master_Matrix_Data__c record : finalListProductSampleMasterMatrixData) {
            if (record.Product__r != null) {
                productIds.add(record.Product__r.Id);
            }
        }
        System.debug('productIds '+ productIds);
        List<Product_Stock_Data__c> productStockData = [Select Id, Product_ID__c, Stock_level__c FROM Product_Stock_Data__c WHERE Product_ID__c IN: productIds];
        
        //Map<String, List<Sample_Master_Matrix_Data__c>> resultMap = new Map<String, List<Sample_Master_Matrix_Data__c>>();
        
        // Prepare a map for faster stock level lookup
        Map<Id, Product_Stock_Data__c> stockMap = new Map<Id, Product_Stock_Data__c>();
        for (Product_Stock_Data__c stock : productStockData) {
            stockMap.put(stock.Product_ID__c, stock);
        }
        
        // Build final wrapper list
        //List<SampleMasterMatrixWrapper> wrappedResults = new List<SampleMasterMatrixWrapper>();
        for (Sample_Master_Matrix_Data__c matrix : finalListProductSampleMasterMatrixData) {
            Decimal stockLevel = null;
            if (matrix.Product__r != null && stockMap.containsKey(matrix.Product__r.Id)) {
                stockLevel = stockMap.get(matrix.Product__r.Id).Stock_level__c;
            }
            wrappedResults.add(new SampleMasterMatrixWrapper(matrix, stockLevel));
        }
        System.debug(wrappedResults);
       // return wrappedResults;
      
       resultWrapper.totalRecords = totalRecords;
       resultWrapper.records = wrappedResults;
       return resultWrapper;
    }
    
    /*************************************************************** 
====================================================== 
Purpose:Search product Names based on user Input
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   30/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
    @AuraEnabled(cacheable = true)
    public static List<String> searchProductNames(String searchTerm)
    {        
        // Query Product Names
        String searchTermFilter = searchTerm.replace('*', '%');
        List<Sample_Master_Matrix_Data__c> products = [
            SELECT Product__r.Name
            FROM Sample_Master_Matrix_Data__c
            WHERE Product__r.Name LIKE :('%' + searchTermFilter + '%') 
            ORDER BY Name
            LIMIT 25
        ];
      
        Set<String> uniqueProductNames = new Set<String>();
        
        // Populate the Set to remove duplicates
        for (Sample_Master_Matrix_Data__c product : products) {
            uniqueProductNames.add(product.Product__r.Name);
        }
  		System.debug(uniqueProductNames);
        return new List<String>(uniqueProductNames);
    }   
    
    /*************************************************************** 
====================================================== 
Purpose:Search categries based on user Input
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<String> searchCategories(String searchTerm) {   
        
        String searchTermFilter = searchTerm.replace('*', '%');
        // Query categories
        List<Sample_Master_Matrix_Data__c> categories = [
            SELECT Product_Category_ID__r.Name
            FROM Sample_Master_Matrix_Data__c
            WHERE Product_Category_ID__r.Name LIKE :('%' + searchTermFilter + '%') 
            AND Product_Category_ID__r.Level__c = '3 - Product'
            ORDER BY Product_Category_ID__r.Name
            LIMIT 25
        ];
        
        // Use a Set to ensure uniqueness based on a specific field
        Set<String> uniqueCategories = new Set<String>();
        
        // Populate the Set to remove duplicates
        for (Sample_Master_Matrix_Data__c category : categories) {
            uniqueCategories.add(category.Product_Category_ID__r.Name);
        }
       
        return new List<String>(uniqueCategories);
    }
    
    
    
    /*************************************************************** 
====================================================== 
Purpose: Retrive UOM standard data based on user input values
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<UoM_Std_Data__c> searchUoM(String searchTerm){
        
        String searchTermFilter = searchTerm.replace('*', '%');

        return [
            SELECT Id, Name 
            FROM UoM_Std_Data__c  
            WHERE Name LIKE :('%'+searchTermFilter+'%') OR UOM_Code__c  LIKE :('%'+searchTermFilter+'%')
            ORDER BY Name 
            Limit 25
        ];
        
    }
    
    
    /*************************************************************** 
====================================================== 
Purpose: Wrapper class to send the data to LWC
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
    
    public class SampleMasterMatrixWrapper {
        @AuraEnabled public Sample_Master_Matrix_Data__c matrixRecord;
        @AuraEnabled public Decimal stockLevel;
        
        public SampleMasterMatrixWrapper(Sample_Master_Matrix_Data__c matrixRecord, Decimal stockLevel) {
            this.matrixRecord = matrixRecord;
            this.stockLevel = stockLevel;
        }
    }
    
    public class SampleSearchResult {
    @AuraEnabled public Integer totalRecords;
    @AuraEnabled public List<SampleMasterMatrixWrapper> records;
}

    /*************************************************************** 
====================================================== 
Purpose: To validate the ticked products
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
    @AuraEnabled
    public static selectedProductWrapper validateTickedProducts(
        String productId, 
        String plantId,
        String unitOfMeasure, 
        String oldSelectedProductJson 
    ) {
        System.debug('Product ID: ' + productId + ', Plant ID: ' + plantId + ', Unit of Measure: ' + unitOfMeasure);
        
        
        selectedProductWrapper oldSelectedProduct;
        
        if (!String.isBlank(oldSelectedProductJson)) {
            oldSelectedProduct = (selectedProductWrapper)JSON.deserialize(oldSelectedProductJson, selectedProductWrapper.class);
        }
        
        System.debug(oldSelectedProduct);
        
        // Step 1: Get Salesforce Order Type Determination
        List<Salesforce_Order_Type_Determination__c> lstSalesforceOrderTypeDeterminations = [
            SELECT Id, Salesforce_Order_Type__c, Sales_Org__c, Distribution_Channel__c, Division__c, 
            Shipping_Condition__c, Delivery_Block__c, Default_Product__c
            FROM Salesforce_Order_Type_Determination__c
            WHERE Plant_ID__c = :plantId 
            AND Active__c = true
            LIMIT 1
        ];
        
        if (lstSalesforceOrderTypeDeterminations.isEmpty()) {
            throw new AuraHandledException('No Salesforce Order Type Determination found for the given plant.');
        }
        
        Salesforce_Order_Type_Determination__c orderType = lstSalesforceOrderTypeDeterminations[0];
        
        if(orderType.Default_Product__c!=null)
        {
            productId = orderType.Default_Product__c;
        }
        // Step 2: Get Product Sales Data
        //if(orderType.Salesforce_Order_Type__c == 'ZPLS' ){
        List<Product_Sales_Data__c> lstProductSalesData = [
            SELECT Id, Item_Category_Group__c 
            FROM Product_Sales_Data__c
            WHERE Product_ID__c = :productId
            AND Sales_Organization__c = :orderType.Sales_Org__c
            AND Distribution_Channel__c = :orderType.Distribution_Channel__c
            LIMIT 1
        ];
        
         if (lstProductSalesData.isEmpty() && orderType.Salesforce_Order_Type__c == 'ZPLS') {
             throw new AuraHandledException('The data required for the Product Sales Data is not currently maintained. Please contact the Product Maintenance team for support.');
         }
                    Product_Sales_Data__c productSalesData;
            List<SAP_S4_Order_Type_Determination__c> lstS4Determinations = new List<SAP_S4_Order_Type_Determination__c>();
            SAP_S4_Order_Type_Determination__c s4OrderType = new SAP_S4_Order_Type_Determination__c();

            if (lstProductSalesData != null && !lstProductSalesData.isEmpty()) {
                productSalesData = lstProductSalesData[0];

                // Step 3: Get S4 Order Type Determination
                lstS4Determinations = [
                    SELECT Id, S4_Order_Type__c, Item_Category__c
                    FROM SAP_S4_Order_Type_Determination__c
                    WHERE Salesforce_Order_Type__c = :orderType.Salesforce_Order_Type__c
                    AND Item_Category_Group__c = :productSalesData.Item_Category_Group__c 
                    AND Active__c = true
                    LIMIT 1
                ];
                
               if (lstS4Determinations.isEmpty() && orderType.Salesforce_Order_Type__c == 'ZPLS') {
                   throw new AuraHandledException('The data required for the S4 order type is not currently maintained. Please contact the Product Maintenance team for support.');
               } 
            }

            // Safely assign the result
            if (lstS4Determinations != null && !lstS4Determinations.isEmpty()) {
                s4OrderType = lstS4Determinations[0];
            } else {
                s4OrderType.S4_Order_Type__c = null;
                s4OrderType.Item_Category__c = null;
            }

     
        //get Price book Id for the selected Product
        PricebookEntry pricebookEntry = new PricebookEntry();
        if(orderType.Default_Product__c != null){
            pricebookEntry = getPriceBookEntryId(orderType.Default_Product__c);
        }
        else{
             pricebookEntry = getPriceBookEntryId(productId);
        }
        String pricebookEntryId = pricebookEntry.Id;
        String pricebookId = pricebookEntry.Pricebook2Id;
        
        
        // Step 4: Compare with old selection if provided
        selectedProductWrapper newSelection = new selectedProductWrapper(
            orderType.Salesforce_Order_Type__c,
            s4OrderType.S4_Order_Type__c,
            orderType.Shipping_Condition__c,
            orderType.Delivery_Block__c,
            plantId,
            orderType.Sales_Org__c,
            orderType.Distribution_Channel__c,
            orderType.Division__c,
            s4OrderType.Item_Category__c,
            pricebookEntryId,
            pricebookId, 
            orderType.Default_Product__c
        );
        
        //step 5: check the valid UoM
        List<String> lstProduct = new List<String>{productId};
            
            List<String> lstValidUoMs = Syn_UtilityClass.getValidUoMListforProduct(lstProduct)[0].validUoMs;
        
        if (!lstValidUoMs.isEmpty()) {
            
            if (!lstValidUoMs.contains(unitOfMeasure)) {
                // Show error message or throw exception
                throw new AuraHandledException('Selected Unit of Measure is not valid for the selected product, please contact your Product Manager.');
            }
        }
        
        System.debug('newSelection'+' '+newSelection + ' '+oldSelectedProduct);
        if (oldSelectedProduct != null) {
            // Compare all fields
            System.debug('oldSelection'+' '+oldSelectedProduct);
            
            Map<String, Boolean> mismatchMap = new Map<String, Boolean>{
                'Plant'                 => newSelection.plant != oldSelectedProduct.plant,
                'Salesforce Order Type' => newSelection.salesforceOrderType != oldSelectedProduct.salesforceOrderType,
                    'S4 Order Type'         => newSelection.s4OrderType != oldSelectedProduct.s4OrderType,
                    'Shipping Condition'    => newSelection.shippingCondition != oldSelectedProduct.shippingCondition,
                    'Delivery Block'        => newSelection.deliveryBlock != oldSelectedProduct.deliveryBlock
                    
                    };
                        
                        for (String fieldLabel : mismatchMap.keySet()) {
                            if (mismatchMap.get(fieldLabel)) {
                                System.debug(fieldLabel);
                                throw new AuraHandledException(fieldLabel + ' does not match the previously selected product.');
                            }
                        }
        }
        
        return newSelection;
    }
    
    /*************************************************************** 
====================================================== 
Purpose: Wrapper class for product validation
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
    
    public class selectedProductWrapper {
        @AuraEnabled public String salesforceOrderType;
        @AuraEnabled public String s4OrderType;
        @AuraEnabled public String shippingCondition;
        @AuraEnabled public String deliveryBlock;
        @AuraEnabled public String plant;
        @AuraEnabled public String salesOrg;
        @AuraEnabled public String distributionChannel;
        @AuraEnabled public String division;
        @AuraEnabled public String s4ItemCategory;
        @AuraEnabled public String pricebookEntryId;
        @AuraEnabled public String pricebookId;
        @AuraEnabled public String defaultProduct;
        
        
        
        // Required for deserialization from LWC
        public selectedProductWrapper() {}
        
        public selectedProductWrapper(String salesforceOrderType, String s4OrderType, String shippingCondition, String deliveryBlock, String plant, String salesOrg, String distributionChannel, String division, String s4ItemCategory, String pricebookEntryId, String pricebookId, String defaultProduct ) {
            this.salesforceOrderType = salesforceOrderType;
            this.s4OrderType = s4OrderType;
            this.shippingCondition = shippingCondition;
            this.deliveryBlock = deliveryBlock;
            this.plant = plant;
            this.salesOrg = salesOrg;
            this.distributionChannel = distributionChannel;
            this.division = division;
            this.s4ItemCategory = s4ItemCategory;
            this.pricebookEntryId = pricebookEntryId;
            this.pricebookId = pricebookId;
            this.defaultProduct = defaultProduct;
        }
    }
    
    /*************************************************************** 
====================================================== 
Purpose: To get the product Pricebook Entry ID and the PriceBook Id
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
    public static PricebookEntry getPriceBookEntryId(String productId)
    {
        List<PricebookEntry> lstPriceBookEntry = [SELECT ID, Pricebook2Id, Product2Id  FROM PricebookEntry WHERE Product2Id = : productId LIMIT 1];
        return lstPriceBookEntry[0];
    }
    
    /*************************************************************** 
====================================================== 
Purpose: If component called from from Order then query the existing order Products
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getOrderItemsFormOrder(Id recordId) {
        System.debug('Record Id: ' + recordId);
        
        if (recordId != null   && recordId.getSObjectType() == Order.sObjectType) {
            System.debug('Inside Order processing block');
            Order order = [SELECT ID, Shipping_Condition__c, Delivery_Block__c FROM Order WHERE Id =: recordId];
            
            List<OrderItem> lstOrderProduct = [
                SELECT Id, Product2Id, Product2.Product_Id__c, Product2.Name, Description, Default_Product_Used__c,
                Product2.Product_Category__r.Name, Quantity, Quantity_UoM__c, Quantity_UoM__r.Name,
                Plant__c, Plant__r.Name, Estimated_Stock__c, 
                Salesforce_Order_Type__c, S4_Order_Type__c, 
                Sales_Organisation__c, 
                Distribution_Channel__c, Division__c, S4_Item_Category__c, 
                Sample_Master_Matrix_Data__c,
                PricebookEntryId, PricebookEntry.Pricebook2Id, 	Sample_Item_Approval_Status__c
                FROM OrderItem
                WHERE OrderId = :recordId
            ];
            
            // Collect unique Matrix IDs
            Set<Id> lstSampleMasterMatrixIds = new Set<Id>();
            for (OrderItem item : lstOrderProduct) {
                if (item.Sample_Master_Matrix_Data__c != null) {
                    lstSampleMasterMatrixIds.add(item.Sample_Master_Matrix_Data__c);
                }
            }
            
            // Map Matrix Data by Id
            Map<Id, Sample_Master_Matrix_Data__c> mapSampleMasterMatrix = new Map<Id, Sample_Master_Matrix_Data__c>();
            if (!lstSampleMasterMatrixIds.isEmpty()) {
                for (Sample_Master_Matrix_Data__c matrix : [
                    SELECT Id, Product__c, Region__c, Min__c, Max__c
                    FROM Sample_Master_Matrix_Data__c
                    WHERE Id IN :lstSampleMasterMatrixIds
                ]) {
                    mapSampleMasterMatrix.put(matrix.Id, matrix);
                }
            }
            
            // Compose the final list
            List<Map<String, Object>> lstOrderProductMap = new List<Map<String, Object>>();
            
            for (OrderItem item : lstOrderProduct) {
                Sample_Master_Matrix_Data__c matrix = 
                    item.Sample_Master_Matrix_Data__c != null 
                    ? mapSampleMasterMatrix.get(item.Sample_Master_Matrix_Data__c) 
                    : null;
                
                lstOrderProductMap.add(new Map<String, Object>{
                    'Id' => matrix?.Id,
                        'productId' => item.Product2Id,
                        'externalProductId' => item.Product2.Product_Id__c,
                        'productName' => item.Product2.Name,
                        'description' => item.Description, 
                        'defaultProductUsed' => item.Default_Product_Used__c,
                        'productCategoryName' => item.Product2.Product_Category__r != null 
                        ? item.Product2.Product_Category__r.Name : null,
                            'possibleQuantity' => item.Quantity,
                            'plantId' => item.Plant__c,
                            'plantName' => item.Plant__r != null ? item.Plant__r.Name : null,
                                'region' => matrix != null ? matrix.Region__c : null,
                                    'minQty' => matrix != null ? matrix.Min__c : null,
                                        'maxQty' => matrix != null ? matrix.Max__c : null,
                                            'estimatedStock' => item.Estimated_Stock__c,
                                            'salesforceOrderType' => item.Salesforce_Order_Type__c,
                                            's4OrderType' => item.S4_Order_Type__c,
                                            'shippingCondition' => order.Shipping_Condition__c,
                                            'deliveryBlock' => order.Delivery_Block__c,
                                            'salesOrg' => item.Sales_Organisation__c,
                                            'distributionChannel' => item.Distribution_Channel__c,
                                            'division' => item.Division__c,
                                            'itemCategory' => item.S4_Item_Category__c,
                                            'pricebookEntryId' => item.PricebookEntryId,
                                            'pricebook2Id' => item.PricebookEntry != null 
                                            ? item.PricebookEntry.Pricebook2Id : null,
                                                'uomId' => item.Quantity_UoM__c,
                                                'uom' => item.Quantity_UoM__r.Name,
                                                'orderProductId' => item.Id,
                                                'approvalStatus' => item.Sample_Item_Approval_Status__c
                                                });
            }
            
            System.debug('Order Product Map: ' + lstOrderProductMap);
            return lstOrderProductMap;
        }
        
        return null;
    }
    

        /*************************************************************** 
====================================================== 
Purpose: If component called from from Order then query the existing order Products
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   08/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
@AuraEnabled(cacheable=true)
public static Name_Value_Pair__mdt getPaginationSize()
{
    Name_Value_Pair__mdt lstPageSize = [SELECT Id, DeveloperName, value__c FROM Name_Value_Pair__mdt WHERE DeveloperName = 'Sample_Prd_Selector_Result_Records_Page' LIMIT 1];
    return lstPageSize;
}
}