SynProdGITV1/force-app/main/default/objects/Order/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSP-176 SS2-T109 Lookup to Plant object</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>Complete Plant Data</description>
    <label>Plant Data</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Plant__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <externalId>true</externalId>
    <label>Plant ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Plant_Team_Data__c/Plant_Team_Data__c.object-meta.xml
<CustomObject>
    <description>Object to store the team associated to a plant.</description>
    <label>Plant Team Data</label>
    <nameField>
        <displayFormat>PTD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plant Team Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Plant_Team_Data__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Record_Type_Name__c</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Plants Team Data</relationshipLabel>
    <relationshipName>Plants_Team_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Plant_Team_Data__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant ID</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Plants Team Data</relationshipLabel>
    <relationshipName>Plants_Team_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Plant_Team_Data__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sample Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Representative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Plant_Team_Data__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plants_Team_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/classes/Syn_RelatedPlantTeamController.cls
/*************************************************************** 
====================================================== 
Purpose: Class to Get Related Plant Team members from the Order
===================================================== 
History: 
AUTHOR     DATE         Reference        Description 
Shyam C   13/08/2025                  Initial Implementation  

***************************************************************/

public class Syn_RelatedPlantTeamController {
	@AuraEnabled(cacheable=true)
    public static List<Plant_Team_Data__c> getPlantTeamMembers(Id orderId) {
        Order ord = [
            SELECT Plant__c
            FROM Order
            WHERE Id = :orderId
            LIMIT 1
        ];
        
        return [
            SELECT Id,
                   Role__c,
                   User__r.Name,
                   Employee__r.Name
            FROM Plant_Team_Data__c
            WHERE Plant_ID__c = :ord.Plant__c
        ];
    }
}