SynProdGITV1/force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Used to capture details errors and processing events.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Log__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <description>The severity of the Error</description>
    <inlineHelpText>The severity of the Error</inlineHelpText>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Fatal</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The Id of the Primary Record this Error relates to</description>
    <inlineHelpText>The Id of the Primary Record this Error relates to</inlineHelpText>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/classes/LoggingFrameworkTest.cls
@isTest
public class LoggingFrameworkTest {
    @isTest static void testLogCreation(){
		//dummy record id
        String recordId = '001254asdf25311234';
        
        Test.startTest();
        //create a log entry
        LoggingFramework.CreateLog('Error', 'Error while creating account', recordId, 'recordInfo', 'method', 'classname', 'stackTrace');
        Test.stopTest();
     
        //ensure there is log created
        List<Log__c> allLogs = [select record_id__c, log_level__c from Log__c];
        System.assertEquals(allLogs?.size() , 1 , 'Number of logs is incorrect.');
        Log__c log = allLogs[0];
        System.assertEquals(log.Record_Id__c, recordId, 'Record Id is not the same.');
    }
}