SynProdGITV1/force-app/main/default/objects/Create_Log__e/Create_Log__e.object-meta.xml
<CustomObject>
    <description>Event to create a log record.</description>
    <label>Create Log</label>
    <pluralLabel>Create Logs</pluralLabel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Create_Log__e/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <description>The severity of the Error</description>
    <inlineHelpText>The severity of the Error</inlineHelpText>
    <label>Log Level</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Create_Log__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The Friendly Error Message</description>
    <inlineHelpText>The Friendly Error Message</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Create_Log__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The Id of the Primary Record this Error relates to</description>
    <inlineHelpText>The Id of the Primary Record this Error relates to</inlineHelpText>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Create_Log__e/fields/Record_Info__c.field-meta.xml
<CustomField>
    <fullName>Record_Info__c</fullName>
    <description>The related record info (e.g. Batch Job Id, Contact Id etc)</description>
    <inlineHelpText>The related record info (e.g. Batch Job Id, Contact Id etc)</inlineHelpText>
    <label>Record Info</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Create_Log__e/fields/Source_Method__c.field-meta.xml
<CustomField>
    <fullName>Source_Method__c</fullName>
    <description>The originating method in the Class or node in the Flow  (e.g. UpdateDivision )</description>
    <inlineHelpText>The originating method in the Class or or node in the Flow  (e.g. UpdateDivision )</inlineHelpText>
    <label>Source Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Create_Log__e/fields/Source_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Name__c</fullName>
    <description>The name of the originating Class or Flow (e.g.  CustomerManagement)</description>
    <inlineHelpText>The name of the originating Class or Flow (e.g.  CustomerManagement)</inlineHelpText>
    <label>Source Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Create_Log__e/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <description>The type of the Source that raised the error e.g Apex, Flow, Integration</description>
    <inlineHelpText>The type of the Source that raised the error e.g Apex, Flow, Integration</inlineHelpText>
    <label>Source Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Create_Log__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The Stack Trace log of the Exception</description>
    <inlineHelpText>The Stack Trace log of the Exception</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SynProdGITV1/force-app/main/default/classes/LoggingFramework.cls
public without sharing class LoggingFramework {
    public static void CreateLog(String logLevel, String message, String recordId, String recordInfo, String classMethod, String className, String stackTrace){
        
        //create new log based on the method inputs
        Create_Log__e newLog = New Create_Log__e();
        newLog.Log_Level__c = logLevel;
        newLog.Message__c = message;
        newLog.Record_Id__c = recordId;
        newLog.Record_Info__c = recordInfo;
        newLog.Source_Method__c = classMethod;
        newLog.Source_Name__c = className;
        newLog.Source_Type__c = 'Apex';
        newLog.Stack_Trace__c = stackTrace;
        
        //publish the event
        Database.SaveResult sr = EventBus.publish(newLog);
        
        if(!sr.isSuccess()){
            System.debug('Failed to publish platform event for log creation.');
        }
    }	
}