SynProdGITV1/force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This will be populated from Flow using Billing Country code. It will be either ASIA, EMEA or AMERICAS</description>
    <inlineHelpText>Auto-populated based on Billing Country</inlineHelpText>
    <label>Region</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Order/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSP-176 SS2-T109 Lookup to Plant object</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSP-176 SS2-T109 Lookup to Plant Object from where the Product will come from</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/OrderItem/fields/Sample_Master_Matrix_Data__c.field-meta.xml
<CustomField>
    <fullName>Sample_Master_Matrix_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Sample Master Matrix data record</description>
    <label>Sample Master Matrix Data</label>
    <referenceTo>Sample_Master_Matrix_Data__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>Complete Plant Data</description>
    <label>Plant Data</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Plant__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <externalId>true</externalId>
    <label>Plant ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product2/fields/Base_UoM__c.field-meta.xml
<CustomField>
    <fullName>Base_UoM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base UoM</label>
    <referenceTo>UoM_Std_Data__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product2/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <description>For ERP products - this will be populated by ERP&apos;s MATNR Number 
For Salesforce Products - this will be populated by Internal Product ID which is an AutoNumber 10000000 onwards
(We might need to turn off the Unique flag during the migration of C4C Products if Product ID will be blank)</description>
    <externalId>true</externalId>
    <inlineHelpText>For ERP products - MATNR 
For Salesforce Product - Internal Product ID (AutoNumber)</inlineHelpText>
    <label>Product Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/fields/Hierarchy_Info__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Info__c</fullName>
    <label>Hierarchy Info</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - Product Hierarchy</fullName>
            </value>
            <value>
                <fullName>2 - Chemical Group</fullName>
            </value>
            <value>
                <fullName>3 - Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/fields/Product_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_ID__c</fullName>
    <externalId>true</externalId>
    <label>Product Category ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Sales_Data__c/Product_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Product Sales Data</label>
    <nameField>
        <displayFormat>PSD-{00000000}</displayFormat>
        <label>Product Sales Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Sales Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Product_Sales_Data__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product ID</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Sales Data</relationshipLabel>
    <relationshipName>Product_Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Stock_Data__c/Product_Stock_Data__c.object-meta.xml
<CustomObject>
    <label>Product Stock Data</label>
    <nameField>
        <displayFormat>PSDM-{00000000}</displayFormat>
        <label>Product Stock Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stock Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Product_Stock_Data__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product ID</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Stock Data</relationshipLabel>
    <relationshipName>Product_Stock_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Stock_Data__c/fields/Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Stock_Level__c</fullName>
    <label>Stock Level</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Salesforce_Order_Type_Determination__c/Salesforce_Order_Type_Determination__c.object-meta.xml
<CustomObject>
    <description>Object to store the mapping between Sample Product and &quot;Plant, Salesforce order type, Sales Area, etc&quot;</description>
    <label>Salesforce Order Type Determination Data</label>
    <nameField>
        <displayFormat>SOT-{00000000}</displayFormat>
        <label>Salesforce Order Type Determinat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Order Type Determination</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Salesforce_Order_Type_Determination__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to plant data</description>
    <label>Plant ID</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipName>Salesforce_Order_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/Sample_Master_Matrix_Data__c.object-meta.xml
<CustomObject>
    <label>Sample Master Matrix Data</label>
    <nameField>
        <label>Sample Master Matrix Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Master Matrix Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Min__c.field-meta.xml
<CustomField>
    <fullName>Min__c</fullName>
    <label>Min</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plant ID</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Product_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Only Product Categories are allowed</inlineHelpText>
    <label>Product Category ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>3 - Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region field for region specific products</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASIA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Sampling_Status__c.field-meta.xml
<CustomField>
    <fullName>Sampling_Status__c</fullName>
    <label>Sampling Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01 - In Preparation</fullName>
            </value>
            <value>
                <fullName>02 - Active</fullName>
            </value>
            <value>
                <fullName>03 - Blocked</fullName>
            </value>
            <value>
                <fullName>04 - Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>UoM_Std_Data__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/UoM_Std_Data__c/UoM_Std_Data__c.object-meta.xml
<CustomObject>
    <label>UoM Std Data</label>
    <nameField>
        <label>Measurement Unit Text</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UoM Std Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/UoM_Std_Data__c/fields/Internal_UoM_Code__c.field-meta.xml
<CustomField>
    <fullName>Internal_UoM_Code__c</fullName>
    <description>Internal UoM Code - will be used for sending and receiving the Order Item UoM for Order Interface</description>
    <externalId>true</externalId>
    <inlineHelpText>Internal UoM Code - will be used for sending and receiving the Order Item UoM for Order Interface</inlineHelpText>
    <label>Internal UoM Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/UoM_Std_Data__c/fields/UOM_Code__c.field-meta.xml
<CustomField>
    <fullName>UOM_Code__c</fullName>
    <description>ISO Code</description>
    <externalId>true</externalId>
    <inlineHelpText>ISO Code - this will be used in Material integration and migration</inlineHelpText>
    <label>UOM Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/classes/Syn_ProductSelectorControllerTest.cls
/*************************************************************** 
====================================================== 
Purpose:  Test Class for Syn_ProductSelectorController
=================================================== 
History:  
AUTHOR     DATE 	    Reference 	     Description 
Vishal S  29/04/2025    SSP-353	    Initial Implementation	 
***************************************************************/
@isTest
public class Syn_ProductSelectorControllerTest {
    
    @testSetup
   public static void setupData(){
        
        //setup PriceBook
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPricebook;
        
        // Create Unit of Measure
        UoM_Std_Data__c uom = new UoM_Std_Data__c(Name = 'Kilogram', UOM_Code__c = 'KGM', Internal_UoM_Code__c = 'KG' );
        insert uom;
        
        // Create Product Category
        Product_Category__c category = new Product_Category__c(Name = 'Chemicals', Product_Category_Id__c ='Test_PC_001', Level__c = '3 - Product', Hierarchy_Info__c = 'Dispersion polymer - PA_Pure Acrylic');
        insert category;
        
        // Create Product
        Product2 product = new Product2(Name = 'Test Product', Product_Id__c = 'Test_P001', Base_UoM__c = uom.Id , Product_Category__c = category.Id, StockKeepingUnit = 'KG');
        insert product;
        
        System.debug('pb: '+ standardPricebook); 
        PricebookEntry existingPbe;
        
        List<PricebookEntry> existingEntries = [
            SELECT Id, UnitPrice FROM PricebookEntry 
            WHERE Product2Id = :product.Id AND Pricebook2Id = :standardPricebook.Id  AND CurrencyIsoCode = 'GBP'
            LIMIT 1
        ];
        
        System.debug(existingEntries);
        
        if (existingEntries.isEmpty()) {
            // Add if not present
            existingPbe = new PricebookEntry(
                Product2Id = product.Id,
                Pricebook2Id = standardPricebook.Id,
                UnitPrice = 100,
                IsActive = true,
                CurrencyIsoCode = 'GBP'
            );
            insert existingPbe;
        } else {
            // Use existing
            existingPbe = existingEntries[0];
        }
        
        // Create Plant
        Plant__c plant = new Plant__c(Name = 'Plant A');
        insert plant;
        
        // Create Sample Master Matrix Data
        Sample_Master_Matrix_Data__c matrix = new Sample_Master_Matrix_Data__c(
            Product__c = product.Id,
            Product_Category_ID__c = category.Id,
            Unit__c = uom.Id,
            Region__c = 'ASIA',
            Plant_ID__c = plant.Id,
            Min__c = 10,
            Max__c = 100,
            Sampling_Status__c = '02 - Active',
            CurrencyIsoCode = 'GBP'            
        );
        insert matrix;
        
        // Create Stock Data
        Product_Stock_Data__c stock = new Product_Stock_Data__c(
            Product_ID__c = product.Id,
            Stock_level__c = 50,
            Stock_Threshold__c = 1000,
            Product_Stock_External_ID__c = 'Test_P001_ENORICA'
        );
        insert stock;
        
        // Add sales org data
        Sales_Org_Data__c salesOrg = new Sales_Org_Data__c(
            Sales_Org_Id__c = 'SOT1',
            Name =  'Test Org'
        );
        insert salesOrg;
        
        // Add Salesforce Order Type Determination
        Salesforce_Order_Type_Determination__c orderType = new Salesforce_Order_Type_Determination__c(
            Plant_ID__c = plant.Id,
            Salesforce_Order_Type__c = 'ZPLS',
            Sales_Org__c = salesOrg.Id,
            Distribution_Channel__c = '10',
            Division__c = '00',
            Shipping_Condition__c = '03',
            Delivery_Block__c = '02',
            Active__c = true
        );
        insert orderType;
        
        // Add Product Sales Data
        Product_Sales_Data__c salesData = new Product_Sales_Data__c(
            Product_ID__c = product.Id,
            Sales_Organization__c = salesOrg.Id,
            Distribution_Channel__c = '10',
            Item_Category_Group__c = 'NORM',
            Product_Sales_Ext_ID__c = 'Test_P001_SOT1_10'
        );
        insert salesData;
        
        // Add SAP S4 Order Type Determination
        SAP_S4_Order_Type_Determination__c s4OrderType = new SAP_S4_Order_Type_Determination__c(
            Salesforce_Order_Type__c = 'ZPLS',
            Item_Category_Group__c = 'NORM',
            S4_Order_Type__c = 'ZSAM',
            Item_Category__c = 'ZSAF',
            Active__c = true
        );
        insert s4OrderType;
        
        // Setup Account Data
        Account acc = new Account(Name = 'Test Account', BillingCountry='United Kingdom');
        insert acc;
        
        // Set up Order
        Order order = new Order(
            Name = 'Test Order',
            AccountId = acc.Id, // Dummy value for required field
            EffectiveDate = Date.today(),
            Status = 'Draft',
            Shipping_Condition__c = '03',
            Delivery_Block__c = '02',
            Pricebook2Id = pricebookId
        );
        insert order;
        
        // set up OrderItem
        OrderItem orderItem = new OrderItem(
            OrderId = order.Id,
            Quantity = 5,
            Total_Price_Internal__c = 100,
            PricebookEntryId = existingPbe.Id,
            Product2Id = product.Id,
            Quantity_UoM__c = uom.Id,
            Estimated_Stock__c = 25,
            Salesforce_Order_Type__c = 'ZOR',
            S4_Order_Type__c = 'ZSAM',
            Sales_Organisation__c = salesOrg.Id,
            Distribution_Channel__c = '10',
            Division__c = '00',         
            S4_Item_Category__c = 'ZSAF',
            Sample_Master_Matrix_Data__c = matrix.Id
        );
        insert orderItem;
        
    }
    
    @isTest
    static void testSearchProducts_withAllParams() {
        Test.startTest();
        Syn_ProductSelectorController.SampleSearchResult results = Syn_ProductSelectorController.searchProducts(
            'Test', 'Chemicals', 'Kilogram', '10', 'ASIA', 1, 10
        );
        Test.stopTest();
        
        System.assertNotEquals(0, results.records.size(), 'Should return matching product');
        System.assertEquals(50, results.records[0].stockLevel, 'Stock level should match inserted data');
    }
    
    @isTest
    static void testSearchProducts_withNoRequiredQuantity() {
        Syn_ProductSelectorController.SampleSearchResult results = Syn_ProductSelectorController.searchProducts(
            'Test', null, null, null, null, 1, 10
        );
        System.assert(results.records.size() > 0, 'Should return at least one product without quantity filter');
    }
    
    @isTest
    static void testSearchCategories() {
        List<String> lstCategories = Syn_ProductSelectorController.searchCategories('Chem');
        System.assert(lstCategories.contains('Chemicals'), 'Should include matching category name');
    }
    
    @isTest
    static void testSearchProductName(){
        
        List<String> lstProducts = Syn_ProductSelectorController.searchProductNames('Test P');
         System.assert(lstProducts.contains('Test Product'), 'Should include matching category name');
    }
    
    @isTest
    static void testSearchUoM() {
        List<UoM_Std_Data__c> uoms = Syn_ProductSelectorController.searchUoM('Kilo');
        System.assertEquals(1, uoms.size(), 'Should return one matching UoM');
        System.assertEquals('Kilogram', uoms[0].Name, 'UoM name should match');
    }
    
    @isTest
    static void testGetPriceBookEntryId() {
        // Get the inserted Product2 from setup
        Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'Test Product' LIMIT 1];
        
        Test.startTest();
        PricebookEntry result = Syn_ProductSelectorController.getPriceBookEntryId(prod.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Should return a PricebookEntry');
        System.assertEquals(prod.Id, result.Product2Id, 'Returned entry should belong to the test product');
    }
    
    @isTest
    static void testValidateTickedProducts_Success() {
        
        Product2 product = [SELECT Id FROM Product2 WHERE Name = 'Test Product' LIMIT 1];
        Plant__c plant = [SELECT Id FROM Plant__c WHERE Name = 'Plant A' LIMIT 1];
        UoM_Std_Data__c uom = [SELECT Id FROM UoM_Std_Data__c WHERE Name = 'Kilogram' LIMIT 1];
        
        Test.startTest();
        Syn_ProductSelectorController.selectedProductWrapper result = Syn_ProductSelectorController.validateTickedProducts(
            product.Id,
            plant.Id,
            uom.Id,
            null
        );
        Test.stopTest();
        
        // Assert
        System.assertEquals('ZPLS', result.salesforceOrderType, 'Salesforce Order Type should match');
        System.assertEquals('ZSAM', result.s4OrderType, 'S4 Order Type should match');
        
    }
    
    @isTest
    static void testValidateTickedProducts_mismatchShouldThrow() {
        Product2 product = [SELECT Id FROM Product2 WHERE Name = 'Test Product' LIMIT 1];
        Plant__c plant = [SELECT Id FROM Plant__c WHERE Name = 'Plant A' LIMIT 1];
        UoM_Std_Data__c uom = [SELECT Id FROM UoM_Std_Data__c WHERE Name = 'Kilogram' LIMIT 1];
        
        // Reuse previous inserts or query if needed
        Salesforce_Order_Type_Determination__c orderType = [SELECT Id, Salesforce_Order_Type__c, Sales_Org__c, Plant_ID__c, Distribution_Channel__c, Division__c, Shipping_Condition__c, Delivery_Block__c FROM Salesforce_Order_Type_Determination__c LIMIT 1];
        Product_Sales_Data__c salesData = [SELECT Id, Item_Category_Group__c FROM Product_Sales_Data__c LIMIT 1];
        SAP_S4_Order_Type_Determination__c s4OrderType = [SELECT Id, S4_Order_Type__c, Item_Category__c FROM SAP_S4_Order_Type_Determination__c LIMIT 1];
        
        // Create a wrapper with mismatching field
        Syn_ProductSelectorController.selectedProductWrapper oldWrapper = new Syn_ProductSelectorController.selectedProductWrapper(
            'DIFFERENT', // mismatching salesforceOrderType
            s4OrderType.S4_Order_Type__c,
            orderType.Shipping_Condition__c,
            orderType.Delivery_Block__c,
            plant.Id,
            orderType.Sales_Org__c,
            orderType.Distribution_Channel__c,
            orderType.Division__c,
            s4OrderType.Item_Category__c,
            'dummyId',
            'dummyPBId',
            'true'
        );
        
        String jsonWrapper = JSON.serialize(oldWrapper);
        Boolean exceptionThrown = false;
        
        System.debug(plant.Id+ ' plant Id: '+ orderType.Plant_ID__c);
        
        Test.startTest();
        try {
            Syn_ProductSelectorController.validateTickedProducts(product.Id, plant.Id, uom.Id, jsonWrapper);
            System.assert(false, 'Expected an AuraHandledException due to mismatch');
        } catch (AuraHandledException e) {
            exceptionThrown = true;
        }
        System.assert(exceptionThrown, 'Expected an AuraHandledException');
        Test.stopTest();
    }
    
      @isTest
static void testGetOrderItemsFormOrder() {

    // get Product
    Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = 'Test Product' LIMIT 1];
  
    // get Order
    Order order = [SELECT Id, Name FROM Order WHERE  Name = 'Test Order' LIMIT 1];
         
    Test.startTest();
    List<Map<String, Object>> result = Syn_ProductSelectorController.getOrderItemsFormOrder(order.Id);
    Test.stopTest();

    System.assertNotEquals(null, result, 'Result should not be null');
    System.assertEquals(1, result.size(), 'Should return one order item');
    System.assertEquals(product.Id, result[0].get('productId'), 'Product ID should match');
    System.assertEquals('ASIA', result[0].get('region'), 'Region should match matrix data');
}

    
}