SynProdGITV1/force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>Complete Plant Data</description>
    <label>Plant Data</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Plant__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <externalId>true</externalId>
    <label>Plant ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product2/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <description>For ERP products - this will be populated by ERP&apos;s MATNR Number 
For Salesforce Products - this will be populated by Internal Product ID which is an AutoNumber 10000000 onwards
(We might need to turn off the Unique flag during the migration of C4C Products if Product ID will be blank)</description>
    <externalId>true</externalId>
    <inlineHelpText>For ERP products - MATNR 
For Salesforce Product - Internal Product ID (AutoNumber)</inlineHelpText>
    <label>Product Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/fields/Hierarchy_Info__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Info__c</fullName>
    <label>Hierarchy Info</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - Product Hierarchy</fullName>
            </value>
            <value>
                <fullName>2 - Chemical Group</fullName>
            </value>
            <value>
                <fullName>3 - Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/fields/Product_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_ID__c</fullName>
    <externalId>true</externalId>
    <label>Product Category ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/Sample_Master_Matrix_Data__c.object-meta.xml
<CustomObject>
    <label>Sample Master Matrix Data</label>
    <nameField>
        <label>Sample Master Matrix Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Master Matrix Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sample_Master_Matrix_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plant ID</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Product_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Only Product Categories are allowed</inlineHelpText>
    <label>Product Category ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>3 - Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region field for region specific products</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASIA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Search_Data__c.field-meta.xml
<CustomField>
    <fullName>Search_Data__c</fullName>
    <description>Text field to store the concatenated values of Plant Name, Product Name, Product Category Name, Approver Name, and Region, separated by a delimiter for search and filtering purposes.</description>
    <inlineHelpText>This field automatically combines key values (Plant, Product, Category, Approver, Region)</inlineHelpText>
    <label>Search Data</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/classes/Syn_SampleMatrixSearchDataUpdateTest.cls
/*************************************************************** 
====================================================== 
Purpose: Test class for Syn_UpdateSearchDataBatch 
===================================================== 
History: 
AUTHOR     DATE 	    Reference 	     Description 
Vishal S   16/06/2025            	     Initial Implementation	 
***************************************************************/ 
@isTest
private class Syn_SampleMatrixSearchDataUpdateTest {

    @IsTest
    static void testExecuteMethod() {
        // Create lookup records
        //setup PriceBook
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPricebook;
        
        // Create Product Category
        Product_Category__c category = new Product_Category__c(Name = 'Chemicals', Product_Category_Id__c ='Test_PC_001', Level__c = '3 - Product', Hierarchy_Info__c = 'Dispersion polymer - PA_Pure Acrylic');
        insert category;
        
        // Create Product
        Product2 product = new Product2(Name = 'Test Product', Product_Id__c = 'Test_P001' , Product_Category__c = category.Id, StockKeepingUnit = 'KG');
        insert product;
        
        System.debug('pb: '+ standardPricebook); 
        PricebookEntry existingPbe;
        
        List<PricebookEntry> existingEntries = [
            SELECT Id, UnitPrice FROM PricebookEntry 
            WHERE Product2Id = :product.Id AND Pricebook2Id = :standardPricebook.Id  AND CurrencyIsoCode = 'GBP'
            LIMIT 1
        ];
        
        System.debug(existingEntries);
        
        if (existingEntries.isEmpty()) {
            // Add if not present
            existingPbe = new PricebookEntry(
                Product2Id = product.Id,
                Pricebook2Id = standardPricebook.Id,
                UnitPrice = 100,
                IsActive = true,
                CurrencyIsoCode = 'GBP'
            );
            insert existingPbe;
        } else {
            // Use existing
            existingPbe = existingEntries[0];
        }
        
        // Create Plant
        Plant__c plant = new Plant__c(Name = 'Plant A');
        insert plant;
        User approver = new User(
            FirstName = 'Test',
            LastName = 'Approver',
            Alias = 'tapprov',
            Email = 'testapprover@example.com',
            Username = 'testapprover' + DateTime.now().getTime() + '@example.com',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert approver;

        // Create main record
        Sample_Master_Matrix_Data__c record = new Sample_Master_Matrix_Data__c(
            Product__c = product.Id,
            Plant_ID__c = plant.Id,
            Product_Category_ID__c = category.Id,
            Region__c = 'ASIA',
            Approver__c = approver.Id
        );
        insert record;

        Test.startTest();
        Database.executeBatch(new Syn_SampleMatrixSearchDataUpdateBatch(), 200);
        Test.stopTest();

        // Validate results
        record = [SELECT Search_Data__c FROM Sample_Master_Matrix_Data__c WHERE Id = :record.Id];
        System.assertEquals('Test_P001 -> Test Product -> Plant A -> Chemicals -> ASIA -> Test Approver', record.Search_Data__c);
    }
}