SynProdGITV1/force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>Complete Plant Data</description>
    <label>Plant Data</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Plant__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <externalId>true</externalId>
    <label>Plant ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product2/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <description>For ERP products - this will be populated by ERP&apos;s MATNR Number 
For Salesforce Products - this will be populated by Internal Product ID which is an AutoNumber 10000000 onwards
(We might need to turn off the Unique flag during the migration of C4C Products if Product ID will be blank)</description>
    <externalId>true</externalId>
    <inlineHelpText>For ERP products - MATNR 
For Salesforce Product - Internal Product ID (AutoNumber)</inlineHelpText>
    <label>Product Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Product_Category__c/fields/Product_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_ID__c</fullName>
    <externalId>true</externalId>
    <label>Product Category ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/Sample_Master_Matrix_Data__c.object-meta.xml
<CustomObject>
    <label>Sample Master Matrix Data</label>
    <nameField>
        <label>Sample Master Matrix Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Master Matrix Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sample_Master_Matrix_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>Plant_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plant ID</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Product_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Only Product Categories are allowed</inlineHelpText>
    <label>Product Category ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Category__c.Level__c</field>
            <operation>equals</operation>
            <value>3 - Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipLabel>Sample Master Matrix Data</relationshipLabel>
    <relationshipName>Sample_Master_Matrix_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region field for region specific products</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASIA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SynProdGITV1/force-app/main/default/objects/Sample_Master_Matrix_Data__c/fields/Search_Data__c.field-meta.xml
<CustomField>
    <fullName>Search_Data__c</fullName>
    <description>Text field to store the concatenated values of Plant Name, Product Name, Product Category Name, Approver Name, and Region, separated by a delimiter for search and filtering purposes.</description>
    <inlineHelpText>This field automatically combines key values (Plant, Product, Category, Approver, Region)</inlineHelpText>
    <label>Search Data</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SynProdGITV1/force-app/main/default/classes/Syn_SampleMatrixSearchDataUpdateBatch.cls
/*************************************************************** 
====================================================== 
Purpose: Update Search Data field of Sample Master Matrix Object
====================================================== 
History: 
AUTHOR     DATE 	         Reference 	         Description 
Vishal S   16/06/2025                         Initial Implementation	 
***************************************************************/ 
public class Syn_SampleMatrixSearchDataUpdateBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
            SELECT Id,
                   Product__r.Name, 
                   Plant_ID__r.Name, 
                   Product_Category_ID__r.Name, 
                   Region__c,
                   Approver__r.FirstName,
                   Approver__r.LastName,
            Product__r.Product_Id__c, Plant_ID__r.Plant_ID__c,
                   Search_Data__c
            FROM Sample_Master_Matrix_Data__c
        ]);
    }

    public void execute(Database.BatchableContext context, List<Sample_Master_Matrix_Data__c> sampleMatrixData) {
        for (Sample_Master_Matrix_Data__c record : sampleMatrixData) {
            List<String> parts = new List<String>();

            if (record.Product__r != null && String.isNotBlank(record.Product__r.Product_Id__c)) 
                parts.add(record.Product__r.Product_Id__c);

            
            
            if (record.Product__r != null && String.isNotBlank(record.Product__r.Name)) 
                parts.add(record.Product__r.Name);

             if (record.Plant_ID__r != null && String.isNotBlank(record.Plant_ID__r.Plant_ID__c)) 
                parts.add(record.Plant_ID__r.Plant_ID__c);
            
            if (record.Plant_ID__r != null && String.isNotBlank(record.Plant_ID__r.Name)) 
                parts.add(record.Plant_ID__r.Name);
            


            if (record.Product_Category_ID__r != null && String.isNotBlank(record.Product_Category_ID__r.Name)) 
                parts.add(record.Product_Category_ID__r.Name);

            if (String.isNotBlank(record.Region__c)) 
                parts.add(record.Region__c);

            if (record.Approver__r != null) {
                String fullName = '';
                if (String.isNotBlank(record.Approver__r.FirstName)) 
                    fullName += record.Approver__r.FirstName + ' ';
                if (String.isNotBlank(record.Approver__r.LastName)) 
                    fullName += record.Approver__r.LastName;
                if (String.isNotBlank(fullName)) 
                    parts.add(fullName.trim());
            }

            String concatenated = String.join(parts, ' -> ');
            if (record.Search_Data__c != concatenated) {
                record.Search_Data__c = concatenated;
            }
        }

        update sampleMatrixData;
    }

    public void finish(Database.BatchableContext context) {
        System.debug('Batch process for Search_Data__c completed.');
    }
}